// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captchas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptcha = `-- name: CreateCaptcha :one
INSERT INTO captchas (session_id, grid_size, mine_count, grid, revealed, difficulty_level)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING captcha_id, session_id, grid_size, mine_count, grid, revealed, solved, failed, created_at, updated_at, difficulty_level
`

type CreateCaptchaParams struct {
	SessionID       pgtype.UUID
	GridSize        int32
	MineCount       int32
	Grid            [][]int32
	Revealed        [][]bool
	DifficultyLevel pgtype.Int4
}

func (q *Queries) CreateCaptcha(ctx context.Context, arg CreateCaptchaParams) (Captcha, error) {
	row := q.db.QueryRow(ctx, createCaptcha,
		arg.SessionID,
		arg.GridSize,
		arg.MineCount,
		arg.Grid,
		arg.Revealed,
		arg.DifficultyLevel,
	)
	var i Captcha
	err := row.Scan(
		&i.CaptchaID,
		&i.SessionID,
		&i.GridSize,
		&i.MineCount,
		&i.Grid,
		&i.Revealed,
		&i.Solved,
		&i.Failed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DifficultyLevel,
	)
	return i, err
}

const getCaptchaBySessionID = `-- name: GetCaptchaBySessionID :one
SELECT captcha_id, session_id, grid_size, mine_count, grid, revealed, solved, failed, created_at, updated_at, difficulty_level
FROM captchas
WHERE session_id = $1 AND created_at >= NOW() - INTERVAL '1 hours' AND (solved = false OR failed = false)
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetCaptchaBySessionID(ctx context.Context, sessionID pgtype.UUID) (Captcha, error) {
	row := q.db.QueryRow(ctx, getCaptchaBySessionID, sessionID)
	var i Captcha
	err := row.Scan(
		&i.CaptchaID,
		&i.SessionID,
		&i.GridSize,
		&i.MineCount,
		&i.Grid,
		&i.Revealed,
		&i.Solved,
		&i.Failed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DifficultyLevel,
	)
	return i, err
}

const getOrCreateCaptcha = `-- name: GetOrCreateCaptcha :one
INSERT INTO captchas (captcha_id, session_id, grid_size, mine_count, grid, revealed, difficulty_level)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (captcha_id) DO NOTHING
RETURNING captcha_id, session_id, grid_size, mine_count, grid, revealed, solved, failed, created_at, updated_at, difficulty_level
`

type GetOrCreateCaptchaParams struct {
	CaptchaID       pgtype.UUID
	SessionID       pgtype.UUID
	GridSize        int32
	MineCount       int32
	Grid            [][]int32
	Revealed        [][]bool
	DifficultyLevel pgtype.Int4
}

func (q *Queries) GetOrCreateCaptcha(ctx context.Context, arg GetOrCreateCaptchaParams) (Captcha, error) {
	row := q.db.QueryRow(ctx, getOrCreateCaptcha,
		arg.CaptchaID,
		arg.SessionID,
		arg.GridSize,
		arg.MineCount,
		arg.Grid,
		arg.Revealed,
		arg.DifficultyLevel,
	)
	var i Captcha
	err := row.Scan(
		&i.CaptchaID,
		&i.SessionID,
		&i.GridSize,
		&i.MineCount,
		&i.Grid,
		&i.Revealed,
		&i.Solved,
		&i.Failed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DifficultyLevel,
	)
	return i, err
}

const purgeOldCaptchas = `-- name: PurgeOldCaptchas :exec
DELETE FROM captchas
WHERE created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) PurgeOldCaptchas(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOldCaptchas)
	return err
}

const updateCaptcha = `-- name: UpdateCaptcha :one
UPDATE captchas
SET revealed = $2, solved = $3, failed = $4, updated_at = NOW()
WHERE captcha_id = $1
RETURNING captcha_id, session_id, grid_size, mine_count, grid, revealed, solved, failed, created_at, updated_at, difficulty_level
`

type UpdateCaptchaParams struct {
	CaptchaID pgtype.UUID
	Revealed  [][]bool
	Solved    pgtype.Bool
	Failed    pgtype.Bool
}

func (q *Queries) UpdateCaptcha(ctx context.Context, arg UpdateCaptchaParams) (Captcha, error) {
	row := q.db.QueryRow(ctx, updateCaptcha,
		arg.CaptchaID,
		arg.Revealed,
		arg.Solved,
		arg.Failed,
	)
	var i Captcha
	err := row.Scan(
		&i.CaptchaID,
		&i.SessionID,
		&i.GridSize,
		&i.MineCount,
		&i.Grid,
		&i.Revealed,
		&i.Solved,
		&i.Failed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DifficultyLevel,
	)
	return i, err
}
