// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
)

const getAppMetrics = `-- name: GetAppMetrics :one
SELECT
    (SELECT COUNT(*) FROM captchas) AS captchas_total,
    (SELECT COUNT(*) FROM captchas WHERE COALESCE(solved, false) = TRUE) AS captchas_solved,
    (SELECT COUNT(*) FROM captchas WHERE COALESCE(solved, false) = FALSE) AS captchas_unsolved,
    (SELECT COUNT(*) FROM captchas WHERE created_at >= NOW() - INTERVAL '1 hour') AS captchas_last_hour,
    (SELECT COUNT(*) FROM sessions) AS sessions_total,
    (SELECT COUNT(*) FROM sessions WHERE COALESCE(is_bot, false) = TRUE) AS sessions_bots,
    (SELECT COUNT(*) FROM sessions WHERE COALESCE(is_bot, false) = FALSE) AS sessions_non_bots
`

type GetAppMetricsRow struct {
	CaptchasTotal    int64
	CaptchasSolved   int64
	CaptchasUnsolved int64
	CaptchasLastHour int64
	SessionsTotal    int64
	SessionsBots     int64
	SessionsNonBots  int64
}

func (q *Queries) GetAppMetrics(ctx context.Context) (GetAppMetricsRow, error) {
	row := q.db.QueryRow(ctx, getAppMetrics)
	var i GetAppMetricsRow
	err := row.Scan(
		&i.CaptchasTotal,
		&i.CaptchasSolved,
		&i.CaptchasUnsolved,
		&i.CaptchasLastHour,
		&i.SessionsTotal,
		&i.SessionsBots,
		&i.SessionsNonBots,
	)
	return i, err
}
