// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Captcha struct {
	CaptchaID       pgtype.UUID
	SessionID       pgtype.UUID
	GridSize        int32
	MineCount       int32
	Grid            [][]int32
	Revealed        [][]bool
	Solved          pgtype.Bool
	Failed          pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DifficultyLevel pgtype.Int4
}

type Session struct {
	SessionID              pgtype.UUID
	IpAddress              string
	UserAgent              string
	RequestCount           pgtype.Int4
	AvgTimeBetweenRequests pgtype.Float8
	IsBot                  pgtype.Bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}
