// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (ip_address, user_agent)
VALUES ($1, $2)
RETURNING session_id, ip_address, user_agent, request_count, avg_time_between_requests, is_bot, created_at, updated_at
`

type CreateSessionParams struct {
	IpAddress string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.IpAddress, arg.UserAgent)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestCount,
		&i.AvgTimeBetweenRequests,
		&i.IsBot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateSession = `-- name: GetOrCreateSession :one
INSERT INTO sessions (session_id, ip_address, user_agent)
VALUES ($1, $2, $3)
ON CONFLICT (session_id)
DO UPDATE SET updated_at = NOW()
RETURNING session_id, ip_address, user_agent, request_count, avg_time_between_requests, is_bot, created_at, updated_at
`

type GetOrCreateSessionParams struct {
	SessionID pgtype.UUID
	IpAddress string
	UserAgent string
}

func (q *Queries) GetOrCreateSession(ctx context.Context, arg GetOrCreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getOrCreateSession, arg.SessionID, arg.IpAddress, arg.UserAgent)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestCount,
		&i.AvgTimeBetweenRequests,
		&i.IsBot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    updated_at = NOW(),
    request_count = request_count + 1,
    avg_time_between_requests =
        CASE
            WHEN request_count = 0 THEN GREATEST(EXTRACT(EPOCH FROM (NOW() - updated_at)) * 1000, 0)
            ELSE (
                COALESCE(avg_time_between_requests, 0) * request_count +
                GREATEST(EXTRACT(EPOCH FROM (NOW() - updated_at)) * 1000, 0)
            ) / (request_count + 1)
        END,
    is_bot =
        CASE
            WHEN is_bot THEN TRUE
            WHEN request_count >= 1 AND (
                    (avg_time_between_requests IS NOT NULL AND avg_time_between_requests > 0 AND avg_time_between_requests < 100) OR
                    (request_count >= 30 AND EXTRACT(EPOCH FROM (NOW() - updated_at)) * 1000 < 60000)
            )
            THEN TRUE
            ELSE is_bot
        END
WHERE session_id = $1
RETURNING session_id, ip_address, user_agent, request_count, avg_time_between_requests, is_bot, created_at, updated_at
`

func (q *Queries) UpdateSession(ctx context.Context, sessionID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestCount,
		&i.AvgTimeBetweenRequests,
		&i.IsBot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
