steps:
    # Build l'image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "europe-west9-docker.pkg.dev/minesweeper-497713/captcha-sweeper-ar/captcha-sweeper:$COMMIT_SHA",
              ".",
          ]

    # Push l'image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "push",
              "europe-west9-docker.pkg.dev/minesweeper-497713/captcha-sweeper-ar/captcha-sweeper:$COMMIT_SHA",
          ]

# Remplace $COMMIT_SHA par un tag fixe si tu préfères (ex: "1.0.0")
images:
    - "europe-west9-docker.pkg.dev/minesweeper-497713/captcha-sweeper-ar/captcha-sweeper:$COMMIT_SHA"
